/**
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Cyclic (De Bruijn) patterns: generate one, and find where a fragment sits in it.
 *
 * CyberChef has `Generate De Bruijn Sequence`, which is the half you need first and the half that
 * is useless on its own. The point of a cyclic pattern is the round trip: overflow a buffer with
 * it, read four bytes back out of the crashed register, and learn the offset. Without the lookup
 * there is nothing to do with the sequence but look at it.
 *
 * This is pwntools' `cyclic`/`cyclic_find`, which is the encoding every exploitation workflow
 * already speaks -- lowercase alphabet, subsequence length 4 by default -- so a pattern generated
 * here matches one generated by pwntools, and an offset found here is the offset pwntools reports.
 * Deriving from pwntools (MIT); see THIRD-PARTY-NOTICES.md.
 *
 * @author DoubleGate
 * @license GPL-3.0-or-later
 */

import { z } from "zod";
import { createInputError } from "../errors.mjs";

/** pwntools' default alphabet. Kept identical so patterns are interchangeable with it. */
const DEFAULT_ALPHABET = "abcdefghijklmnopqrstuvwxyz";

/**
 * A De Bruijn sequence B(k, n) over `alphabet`, truncated to `length`.
 *
 * Every subsequence of length `n` appears exactly once, which is the property that makes an
 * offset recoverable from any `n` consecutive bytes.
 *
 * @param {string} alphabet - Symbols to draw from.
 * @param {number} n - Subsequence length.
 * @param {number} length - How many symbols to emit.
 * @returns {string} The sequence.
 */
function deBruijn(alphabet, n, length) {
    const k = alphabet.length;
    const a = new Array(k * n).fill(0);
    const out = [];

    // The standard recursive construction, left recursive. Depth is bounded by `n` -- the
    // subsequence length, capped at 8 -- and NOT by the pattern length, so a 1 MB pattern nests
    // no deeper than an 8-byte one. An explicit stack would buy nothing here.
    const db = (t, p) => {
        if (out.length >= length) return;
        if (t > n) {
            if (n % p !== 0) return;
            for (let i = 1; i <= p && out.length < length; i++) out.push(alphabet[a[i]]);
            return;
        }
        a[t] = a[t - p];
        db(t + 1, p);
        for (let j = a[t - p] + 1; j < k; j++) {
            a[t] = j;
            db(t + 1, t);
        }
    };
    db(1, 1);
    return out.join("");
}

/**
 * Where a fragment first appears in the pattern.
 *
 * @param {string} pattern - The generated sequence.
 * @param {string} fragment - The bytes read back, as text.
 * @param {number} n - Subsequence length the pattern was built for.
 * @returns {{offset: number, matched: string}|null} The offset, or null if absent.
 */
function findOffset(pattern, fragment, n) {
    // Only the first `n` symbols are unique, so a longer fragment is truncated rather than
    // rejected -- a caller pasting eight bytes from a 64-bit register is doing the normal thing.
    const needle = fragment.length > n ? fragment.slice(0, n) : fragment;
    // SHORTER than `n` is a different matter: uniqueness is a property of length-`n` windows only.
    // With n=4, "aa" occurs 282 times in a 1024-byte pattern, and `indexOf` reported the first of
    // them as *the* offset -- a confident wrong overflow offset, which is the single failure this
    // tool exists to prevent. Reported as ambiguous rather than answered.
    if (needle.length < n) return { ambiguous: true, matched: needle };
    const at = pattern.indexOf(needle);
    return at === -1 ? null : { offset: at, matched: needle };
}

/**
 * Interpret the fragment a caller pasted.
 *
 * Registers are usually read as hex, and little-endian architectures print them reversed relative
 * to memory order. Getting this wrong is the classic way to be off by nothing at all and conclude
 * the pattern is broken, so both readings are reported rather than one being guessed at.
 *
 * @param {string} value - What the caller supplied.
 * @param {string} format - `Text`, `Hex` or `Auto`.
 * @returns {Array<{reading: string, text: string}>} Candidate readings, most likely first.
 */
function fragmentReadings(value, format) {
    const trimmed = value.trim();
    const readings = [];
    const asText = () => readings.push({ reading: "text", text: trimmed });
    const asHex = (strict = false) => {
        const hex = trimmed.replace(/^0x/i, "").replace(/[\s_]/g, "");
        if (!/^[0-9a-f]+$/i.test(hex) || hex.length % 2) {
            // In Auto mode this is just "not hex, try text". Under an explicit `Hex` it is a parse
            // failure, and staying silent made the caller reach the "does not appear in the
            // pattern" error further down -- which sent them to check the pattern length and
            // alphabet, both of which were fine. Say what actually went wrong.
            if (strict) {
                throw createInputError(
                    "fragment_format=Hex needs an even number of hexadecimal digits, optionally " +
                    "prefixed with 0x. Use fragment_format=Text if the fragment is literal bytes.",
                    { fragment: trimmed.slice(0, 40), digits: hex.length });
            }
            return;
        }
        const bytes = hex.match(/../g).map(h => parseInt(h, 16));
        readings.push({ reading: "hex, big-endian", text: String.fromCharCode(...bytes) });
        readings.push({ reading: "hex, little-endian", text: String.fromCharCode(...bytes.reverse()) });
    };
    if (format === "Text") asText();
    else if (format === "Hex") asHex(true);
    else {
        // Auto: a bare hex-looking string is far more often a register dump than four letters that
        // happen to be hex digits -- but "dead" and "face" ARE valid fragments, so text is offered
        // too rather than discarded.
        asHex();
        asText();
    }
    return readings;
}

export default {
    name: "cyclic_pattern",
    title: "Cyclic pattern",
    category: "Analysis",
    description:
        "Generate a De Bruijn (cyclic) pattern, or find the offset of a fragment within one. " +
        "Compatible with pwntools' cyclic/cyclic_find, so patterns and offsets are interchangeable " +
        "with it. Use mode=find with the bytes recovered from a crashed register to get the " +
        "overflow offset; hex input is interpreted as both big- and little-endian, because a " +
        "register dump is usually reversed relative to memory.",
    annotations: {
        title: "Cyclic pattern",
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
    },
    inputSchema: z.object({
        mode: z.enum(["generate", "find"]).describe("Generate a pattern, or find an offset in one."),
        length: z.number().int().min(1).max(1048576).default(1024)
            .describe("generate: how many bytes to produce. find: how long the pattern was."),
        // A fragment is a register value or a handful of bytes, and `length` is already bounded at
        // 1 MB -- a fragment larger than the pattern cannot be in it.
        fragment: z.string().max(4096).optional()
            .describe("find: the bytes recovered, as text or hex (e.g. \"aabc\" or 0x63626161)."),
        "fragment_format": z.enum(["Auto", "Text", "Hex"]).default("Auto")
            .describe("find: how to read `fragment`. Auto tries hex first, then text."),
        "subsequence_length": z.number().int().min(1).max(8).default(4)
            .describe("Bytes of uniqueness: 4 for 32-bit, 8 for 64-bit. Must match the pattern."),
        alphabet: z.string().min(2).max(256).default(DEFAULT_ALPHABET)
            .describe("Symbols to build from. The default matches pwntools.")
    }),

    /**
     * @param {Object} args - Validated arguments.
     * @returns {Promise<Object>} The pattern, or the offsets found.
     */
    async run(args) {
        const { mode, length, fragment, "fragment_format": format,
            "subsequence_length": n, alphabet } = args;

        const symbols = [...new Set(alphabet)].join("");
        if (symbols.length !== alphabet.length) {
            throw createInputError(
                "The alphabet must not repeat a symbol: a repeated symbol breaks the uniqueness " +
                "the pattern depends on, so an offset would be ambiguous.",
                { alphabet, distinct: symbols.length });
        }
        // The sequence B(k, n) has k^n symbols; asking for more than exists means the tail repeats
        // and offsets stop being unique. Refuse rather than return a pattern that silently lies.
        const maxLength = Math.pow(symbols.length, n);
        if (length > maxLength) {
            throw createInputError(
                `An alphabet of ${symbols.length} symbols with subsequence length ${n} can only ` +
                `produce ${maxLength} unique bytes; ${length} were requested. Past that the ` +
                "pattern repeats and offsets are ambiguous. Raise subsequence_length, or use a " +
                "larger alphabet.",
                { requested: length, maximum: maxLength, alphabet: symbols.length, subsequenceLength: n });
        }

        const pattern = deBruijn(symbols, n, length);

        if (mode === "generate") {
            return {
                pattern,
                length: pattern.length,
                "subsequence_length": n,
                alphabet: symbols,
                next: "Feed this to the target, then call this tool again with mode=find and the " +
                    "bytes from the crashed register."
            };
        }

        if (typeof fragment !== "string" || !fragment.trim()) {
            throw createInputError("mode=find needs a `fragment`: the bytes recovered from the crash.",
                { mode });
        }

        const found = [];
        const tooShort = [];
        for (const reading of fragmentReadings(fragment, format)) {
            const hit = findOffset(pattern, reading.text, n);
            if (!hit) continue;
            if (hit.ambiguous) tooShort.push(reading.text);
            else found.push({ reading: reading.reading, fragment: reading.text, offset: hit.offset });
        }

        // Every reading was shorter than the uniqueness window. There IS a first match for each,
        // and returning it would look like an answer -- so refuse, and say which knob to turn.
        if (!found.length && tooShort.length) {
            // The LONGEST reading, so the number quoted back is the one the caller recognises: for
            // "aa" the hex reading is one byte and the text reading is two, and being told
            // "1 byte" about a two-character fragment reads like a different bug.
            const shortest = tooShort.reduce((a, b) => (a.length >= b.length ? a : b));
            throw createInputError(
                `The fragment is ${shortest.length} byte(s) and the pattern is only unique in ` +
                `windows of ${n}. Several positions match, so any offset reported would be a guess ` +
                "rather than the answer. Supply the full width of the register you recovered, or " +
                "lower subsequence_length if the pattern was generated with a smaller one.",
                { fragmentLength: shortest.length, subsequenceLength: n });
        }

        if (!found.length) {
            throw createInputError(
                `"${fragment}" does not appear in a ${length}-byte pattern over ` +
                `${symbols.length} symbols with subsequence length ${n}. Check that the pattern ` +
                "length and alphabet match the one you sent, and that the fragment is the bytes " +
                "themselves rather than an address.",
                { fragment, patternLength: length, subsequenceLength: n });
        }

        return {
            // Several readings can match -- a palindromic fragment matches both endiannesses --
            // so all are reported rather than one being chosen for the caller.
            offsets: found,
            "most_likely": found[0],
            note: found.length > 1 ?
                "More than one reading matched. If you do not know the endianness, try the offsets " +
                "in order." :
                `Offset ${found[0].offset}: that many bytes before the value you recovered.`
        };
    }
};
