// SPDX-License-Identifier: GPL-3.0-or-later
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

// GitHub Pages for a project repository serves from /<repo>/, so `base` is not optional --
// omitting it produces a site whose every internal link 404s only once deployed, which is the
// worst time to find out.
export default defineConfig({
    site: "https://doublegate.github.io",
    base: "/CyberChef-MCP",
    trailingSlash: "always",
    integrations: [
        starlight({
            title: "CyberChef MCP",
            description:
                "Model Context Protocol server for CyberChef: 504 operations as AI-agent tools, " +
                "on protocol revision 2026-07-28.",
            tagline: "GCHQ's Cyber Swiss Army Knife, as tools an AI assistant can call.",
            social: [
                { icon: "github", label: "GitHub", href: "https://github.com/doublegate/CyberChef-MCP" }
            ],
            // Per-page `editUrl` and `lastUpdated` are emitted by collect.mjs from each page's
            // SOURCE file, because a site-wide `editLink.baseUrl` would append the GENERATED path
            // -- sending a contributor to a build artefact whose changes the next build discards --
            // and `lastUpdated: true` would read git history for a regenerated, gitignored file
            // that has none. Generated pages (the tool reference) carry `editUrl: false`, since
            // there is no single file to edit.
            lastUpdated: true,
            favicon: "/favicon.svg",
            customCss: ["./src/styles/custom.css"],
            // Starlight >= 0.39 removed autogenerated sidebar *groups*: a group is now a label
            // plus an `items` array that may contain an autogenerate entry. The older
            // `{ label, autogenerate }` shape fails the config schema outright rather than
            // degrading, which is the right call and worth not re-introducing.
            sidebar: [
                { label: "Start here", items: [{ autogenerate: { directory: "start" } }] },
                { label: "Guides", items: [{ autogenerate: { directory: "guides" } }] },
                { label: "Tool reference", collapsed: true, items: [{ autogenerate: { directory: "reference" } }] },
                { label: "Architecture", items: [{ autogenerate: { directory: "architecture" } }] },
                { label: "Security", items: [{ autogenerate: { directory: "security" } }] },
                { label: "Releases", collapsed: true, items: [{ autogenerate: { directory: "releases" } }] },
                { label: "Decisions", collapsed: true, items: [{ autogenerate: { directory: "decisions" } }] }
            ],
            components: {},
            head: [
                { tag: "meta", attrs: { name: "theme-color", content: "#0b7285" } }
            ]
        })
    ]
});
