name: "Pull Request Checks"

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  core-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set node version
      uses: actions/setup-node@v7
      with:
        node-version: '24'

    - name: Install
      run: |
        npm install
        npm run setheapsize

    - name: Patch Dependencies for Node 22
      run: |
        sed -i 's/new SlowBuffer/Buffer.alloc/g' node_modules/avsc/lib/types.js
        sed -i 's/SlowBuffer/Buffer/g' node_modules/buffer-equal-constant-time/index.js

    - name: Lint
      run: npx grunt lint

    - name: Config Tests
      run: npx grunt configTests

    - name: Unit Tests
      run: |
        npm test
        npm run testnodeconsumer